sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**,functions/test/**
sonar.sources=src,functions/src,functions/test,public,.github,scripts,e2e
sonar.exclusions=**/node_modules/**,functions/lib/**,functions/migration_data/**,dist/**,coverage/**
